import type { DisciplineSeedData, CatSeed, EntrySeed, SeqSeed, CounterSeed } from '../taxonomySeed'

const id = (name: string) => `bjj_${name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/_+$/, '')}`

export function getBjjData(): DisciplineSeedData {
  const categories: CatSeed[] = [
    { id: 'bjj_cat_guards', discipline: 'bjj', name: 'Guard Positions', parentId: null, description: 'All guard types', sortOrder: 1 },
    { id: 'bjj_cat_guard_closed', discipline: 'bjj', name: 'Closed Guard', parentId: 'bjj_cat_guards', description: 'Legs wrapped around opponent', sortOrder: 1 },
    { id: 'bjj_cat_guard_open', discipline: 'bjj', name: 'Open Guard', parentId: 'bjj_cat_guards', description: 'Feet on hips/legs, not closed', sortOrder: 2 },
    { id: 'bjj_cat_guard_half', discipline: 'bjj', name: 'Half Guard', parentId: 'bjj_cat_guards', description: 'One leg entangled', sortOrder: 3 },
    { id: 'bjj_cat_passes', discipline: 'bjj', name: 'Guard Passes', parentId: null, description: 'Techniques to pass the guard', sortOrder: 2 },
    { id: 'bjj_cat_submissions', discipline: 'bjj', name: 'Submissions', parentId: null, description: 'Joint locks and chokes', sortOrder: 3 },
    { id: 'bjj_cat_sub_chokes', discipline: 'bjj', name: 'Chokes', parentId: 'bjj_cat_submissions', description: 'Blood and air chokes', sortOrder: 1 },
    { id: 'bjj_cat_sub_armlocks', discipline: 'bjj', name: 'Arm Locks', parentId: 'bjj_cat_submissions', description: 'Armbar, kimura, americana', sortOrder: 2 },
    { id: 'bjj_cat_sub_leglocks', discipline: 'bjj', name: 'Leg Locks', parentId: 'bjj_cat_submissions', description: 'Heel hook, knee bar, ankle lock', sortOrder: 3 },
    { id: 'bjj_cat_positions', discipline: 'bjj', name: 'Dominant Positions', parentId: null, description: 'Top control positions', sortOrder: 4 },
    { id: 'bjj_cat_sweeps', discipline: 'bjj', name: 'Sweeps', parentId: null, description: 'Reversals from bottom', sortOrder: 5 },
    { id: 'bjj_cat_escapes', discipline: 'bjj', name: 'Escapes', parentId: null, description: 'Escaping bad positions', sortOrder: 6 },
    { id: 'bjj_cat_transitions', discipline: 'bjj', name: 'Transitions', parentId: null, description: 'Moving between positions', sortOrder: 7 },
  ]

  const entries: EntrySeed[] = [
    // --- Guard Positions ---
    {
      id: id('closed_guard'), categoryId: 'bjj_cat_guard_closed', discipline: 'bjj', name: 'Closed Guard',
      japaneseName: null, koreanName: null,
      description: 'Legs wrapped around opponents waist, ankles crossed. Defensive position with many attacks: armbar, triangle, omoplata, sweeps.',
      keyPoints: ['Control posture by pulling head down', 'Break their grips', 'Use hips to create angles', 'Ankles crossed behind their back'],
      commonMistakes: ['Flat on back with no angle', 'Not controlling posture', 'Passive guard play'],
      difficulty: 'beginner', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['guard', 'closed-guard', 'bottom', 'fundamental'], metadata: { hierarchy: 3 }, effectivenessScore: 0.82,
    },
    {
      id: id('butterfly_guard'), categoryId: 'bjj_cat_guard_open', discipline: 'bjj', name: 'Butterfly Guard',
      japaneseName: null, koreanName: null,
      description: 'Seated guard with both feet hooked inside opponents thighs. Excellent for sweeps and underhook battles.',
      keyPoints: ['Hooks inside their thighs', 'Upright posture', 'Underhook is key', 'Elevate with hooks for sweeps'],
      commonMistakes: ['Flat on back', 'No underhook', 'Hooks too shallow'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['guard', 'butterfly', 'open-guard', 'sweeps'], metadata: { hierarchy: 3 }, effectivenessScore: 0.85,
    },
    {
      id: id('de_la_riva'), categoryId: 'bjj_cat_guard_open', discipline: 'bjj', name: 'De La Riva Guard',
      japaneseName: null, koreanName: null,
      description: 'Hook outside of opponents lead leg with your leg, control their ankle. Creates off-balancing and sweep opportunities.',
      keyPoints: ['Hook deep around lead leg', 'Control same-side ankle', 'Other foot on hip or bicep', 'Off-balance them backward'],
      commonMistakes: ['Hook not deep enough', 'No grip on ankle', 'Flat on back'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['guard', 'de-la-riva', 'open-guard', 'hook'], metadata: { hierarchy: 3 }, effectivenessScore: 0.84,
    },
    {
      id: id('spider_guard'), categoryId: 'bjj_cat_guard_open', discipline: 'bjj', name: 'Spider Guard',
      japaneseName: null, koreanName: null,
      description: 'Control opponents arms with sleeve grips while feet push on biceps. Creates distance and sweep/submission setups.',
      keyPoints: ['Grip both sleeves', 'Feet on biceps', 'Extend legs for distance', 'Use lasso variation for more control'],
      commonMistakes: ['Grips too weak', 'Legs not extended', 'No follow-up attacks'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['guard', 'spider', 'open-guard', 'gi'], metadata: { hierarchy: 3 }, effectivenessScore: 0.8,
    },
    {
      id: id('half_guard'), categoryId: 'bjj_cat_guard_half', discipline: 'bjj', name: 'Half Guard',
      japaneseName: null, koreanName: null,
      description: 'One of opponents legs trapped between yours. Can be offensive (underhook, dog fight) or defensive (knee shield).',
      keyPoints: ['Get the underhook', 'Knee shield to create space', 'Come to your side never flat', 'Attack with sweeps or back takes'],
      commonMistakes: ['Flat on back', 'No underhook', 'Passive play'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['guard', 'half-guard', 'bottom', 'versatile'], metadata: { hierarchy: 3 }, effectivenessScore: 0.8,
    },
    {
      id: id('x_guard'), categoryId: 'bjj_cat_guard_open', discipline: 'bjj', name: 'X-Guard',
      japaneseName: null, koreanName: null,
      description: 'Underneath opponent with legs forming an X around one of their legs. Powerful sweep position.',
      keyPoints: ['One hook behind knee, one on hip', 'Control their ankle', 'Elevate and off-balance', 'Multiple sweep directions'],
      commonMistakes: ['Not controlling ankle', 'Hooks not deep', 'Getting stacked'],
      difficulty: 'advanced', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['guard', 'x-guard', 'open-guard', 'sweeps', 'advanced'], metadata: { hierarchy: 3 }, effectivenessScore: 0.86,
    },
    // --- Dominant Positions ---
    {
      id: id('mount'), categoryId: 'bjj_cat_positions', discipline: 'bjj', name: 'Mount',
      japaneseName: null, koreanName: null,
      description: 'Sitting on opponents torso. Highest-value top position. Attacks: armbar, cross-collar choke, americana, mounted triangle.',
      keyPoints: ['Hips low and heavy', 'Grapevine legs for control', 'Post hands for balance', 'Attack when they try to escape'],
      commonMistakes: ['Sitting too high', 'Not grapevining', 'Losing balance when attacking'],
      difficulty: 'beginner', positionContext: 'mount_top', videoUrl: null, thumbnailUrl: null,
      tags: ['position', 'mount', 'dominant', 'top-control'], metadata: { hierarchy: 6 }, effectivenessScore: 0.95,
    },
    {
      id: id('side_control'), categoryId: 'bjj_cat_positions', discipline: 'bjj', name: 'Side Control',
      japaneseName: null, koreanName: null,
      description: 'Perpendicular to opponent, chest-to-chest pressure. Transitions to mount, knee-on-belly, north-south, or back.',
      keyPoints: ['Chest pressure', 'Underhook far arm', 'Crossface with near arm', 'Control hips with your hip'],
      commonMistakes: ['Too much space', 'No crossface', 'Not transitioning'],
      difficulty: 'beginner', positionContext: 'side_control_top', videoUrl: null, thumbnailUrl: null,
      tags: ['position', 'side-control', 'dominant', 'top-control'], metadata: { hierarchy: 5 }, effectivenessScore: 0.88,
    },
    {
      id: id('knee_on_belly'), categoryId: 'bjj_cat_positions', discipline: 'bjj', name: 'Knee on Belly',
      japaneseName: null, koreanName: null,
      description: 'Knee driving into opponents stomach/chest while standing on other foot. Extremely uncomfortable. Opens many attacks.',
      keyPoints: ['Drive knee into solar plexus', 'Grip collar and far arm', 'Stay light on feet', 'Attack when they push knee'],
      commonMistakes: ['Too much weight on knee', 'Not gripping', 'Static play'],
      difficulty: 'intermediate', positionContext: 'knee_on_belly', videoUrl: null, thumbnailUrl: null,
      tags: ['position', 'knee-on-belly', 'dominant', 'pressure'], metadata: { hierarchy: 5.5 }, effectivenessScore: 0.87,
    },
    {
      id: id('back_control'), categoryId: 'bjj_cat_positions', discipline: 'bjj', name: 'Back Control (Back Mount)',
      japaneseName: null, koreanName: null,
      description: 'Behind opponent with hooks in and seatbelt grip. Most dominant position in BJJ.',
      keyPoints: ['Seatbelt grip (over-under)', 'Both hooks in', 'Stay chest-to-back', 'Work for the choke'],
      commonMistakes: ['Losing hooks', 'Crossing feet (ankle lock)', 'Not maintaining seatbelt'],
      difficulty: 'intermediate', positionContext: 'back_control', videoUrl: null, thumbnailUrl: null,
      tags: ['position', 'back-control', 'back-mount', 'dominant'], metadata: { hierarchy: 7 }, effectivenessScore: 0.97,
    },
    {
      id: id('north_south'), categoryId: 'bjj_cat_positions', discipline: 'bjj', name: 'North-South',
      japaneseName: null, koreanName: null,
      description: 'Head-to-head position on top. Heavy chest pressure. Attacks: kimura, north-south choke.',
      keyPoints: ['Heavy chest pressure', 'Control their arms', 'Hips low', 'Transition or attack'],
      commonMistakes: ['Too high', 'Not controlling arms', 'Stalling'],
      difficulty: 'intermediate', positionContext: 'north_south', videoUrl: null, thumbnailUrl: null,
      tags: ['position', 'north-south', 'top-control', 'pressure'], metadata: { hierarchy: 5 }, effectivenessScore: 0.82,
    },
    {
      id: id('turtle'), categoryId: 'bjj_cat_positions', discipline: 'bjj', name: 'Turtle Position',
      japaneseName: null, koreanName: null,
      description: 'Defensive position on hands and knees, protecting neck and arms. Opponent attacks from top or side.',
      keyPoints: ['Tuck chin', 'Elbows tight', 'Protect neck from chokes', 'Look to re-guard or stand up'],
      commonMistakes: ['Staying in turtle too long', 'Exposing neck', 'Not moving to escape'],
      difficulty: 'beginner', positionContext: 'turtle', videoUrl: null, thumbnailUrl: null,
      tags: ['position', 'turtle', 'defensive', 'bottom'], metadata: { hierarchy: 2 }, effectivenessScore: 0.5,
    },
    // --- Submissions ---
    {
      id: id('armbar'), categoryId: 'bjj_cat_sub_armlocks', discipline: 'bjj', name: 'Armbar (Juji Gatame)',
      japaneseName: 'Juji Gatame', koreanName: null,
      description: 'Hyperextend opponents elbow by controlling wrist and applying hip pressure against the joint. Works from guard, mount, side control, back.',
      keyPoints: ['Control the wrist', 'Pinch knees together', 'Hips tight against arm', 'Extend hips for finish', 'Thumb points up'],
      commonMistakes: ['Knees too wide', 'Hips not tight', 'Not controlling wrist', 'Rushing'],
      difficulty: 'beginner', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'armbar', 'arm-lock', 'fundamental', 'versatile'], metadata: { positions: ['guard_bottom', 'mount_top', 'side_control_top', 'back_control'] }, effectivenessScore: 0.92,
    },
    {
      id: id('triangle_choke'), categoryId: 'bjj_cat_sub_chokes', discipline: 'bjj', name: 'Triangle Choke (Sankaku Jime)',
      japaneseName: 'Sankaku Jime', koreanName: null,
      description: 'Legs form triangle around opponents neck and one arm. Cuts blood flow. Works from guard and mount.',
      keyPoints: ['One arm in one arm out', 'Lock ankle behind opposite knee', 'Squeeze knees together', 'Angle off to side', 'Pull head down'],
      commonMistakes: ['Both arms in or out', 'Not angling off', 'Not pulling head down', 'Triangle too loose'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'triangle', 'choke', 'guard'], metadata: { positions: ['guard_bottom', 'mount_top'] }, effectivenessScore: 0.9,
    },
    {
      id: id('rear_naked_choke'), categoryId: 'bjj_cat_sub_chokes', discipline: 'bjj', name: 'Rear Naked Choke (RNC)',
      japaneseName: null, koreanName: null,
      description: 'Highest-percentage submission. From back control: slide arm under chin, grab own bicep, hand behind head, squeeze.',
      keyPoints: ['Get seatbelt first', 'Slide choking arm under chin', 'Grab your own bicep', 'Hand behind their head', 'Squeeze elbows together'],
      commonMistakes: ['Going for choke before securing back', 'Chin strap instead of under chin', 'Squeezing with arms not back'],
      difficulty: 'intermediate', positionContext: 'back_control', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'rnc', 'choke', 'back-control', 'highest-percentage'], metadata: { positions: ['back_control'] }, effectivenessScore: 0.97,
    },
    {
      id: id('guillotine'), categoryId: 'bjj_cat_sub_chokes', discipline: 'bjj', name: 'Guillotine Choke',
      japaneseName: null, koreanName: null,
      description: 'Front headlock choke. Wrap arm around neck, clasp hands, pull upward while arching back.',
      keyPoints: ['Chin in crook of elbow', 'Clasp hands', 'Close guard to prevent pass', 'Arch back and squeeze up'],
      commonMistakes: ['Not closing guard', 'Squeezing sideways not up', 'Opponent passes to side control'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'guillotine', 'choke', 'front-headlock'], metadata: { positions: ['guard_bottom', 'standing'] }, effectivenessScore: 0.88,
    },
    {
      id: id('kimura'), categoryId: 'bjj_cat_sub_armlocks', discipline: 'bjj', name: 'Kimura',
      japaneseName: 'Ude Garami', koreanName: null,
      description: 'Shoulder lock using figure-four grip. Rotate opponents arm behind their back. Works from many positions.',
      keyPoints: ['Figure-four grip on wrist', 'Control their elbow', 'Rotate arm behind back', 'Keep elbow close to body'],
      commonMistakes: ['Grip too loose', 'Not controlling elbow', 'Opponent straightens arm'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'kimura', 'shoulder-lock', 'versatile'], metadata: { positions: ['guard_bottom', 'side_control_top', 'north_south', 'half_guard'] }, effectivenessScore: 0.85,
    },
    {
      id: id('americana'), categoryId: 'bjj_cat_sub_armlocks', discipline: 'bjj', name: 'Americana (Keylock)',
      japaneseName: null, koreanName: null,
      description: 'Shoulder lock from top. Pin wrist to mat, figure-four grip, paint arm upward.',
      keyPoints: ['Pin wrist to mat', 'Figure-four grip', 'Keep elbow pinned', 'Slowly paint arm upward'],
      commonMistakes: ['Not pinning wrist first', 'Rushing', 'Elbow not controlled'],
      difficulty: 'beginner', positionContext: 'mount_top', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'americana', 'keylock', 'shoulder-lock', 'top'], metadata: { positions: ['mount_top', 'side_control_top'] }, effectivenessScore: 0.78,
    },
    {
      id: id('omoplata'), categoryId: 'bjj_cat_sub_armlocks', discipline: 'bjj', name: 'Omoplata',
      japaneseName: null, koreanName: null,
      description: 'Shoulder lock using legs. From guard, swing legs over opponents shoulder, sit up and lean forward.',
      keyPoints: ['Control arm first', 'Swing leg over shoulder', 'Sit up and control waist', 'Lean forward for finish'],
      commonMistakes: ['Opponent rolls through', 'Not controlling waist', 'Not sitting up'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'omoplata', 'shoulder-lock', 'guard'], metadata: { positions: ['guard_bottom'] }, effectivenessScore: 0.8,
    },
    {
      id: id('darce_choke'), categoryId: 'bjj_cat_sub_chokes', discipline: 'bjj', name: 'Darce Choke',
      japaneseName: null, koreanName: null,
      description: 'Arm triangle variation. Thread arm under opponents neck and through their armpit, lock figure-four, squeeze.',
      keyPoints: ['Thread arm deep under neck', 'Through their armpit', 'Lock figure-four on your own bicep', 'Sprawl hips to finish'],
      commonMistakes: ['Not threading deep enough', 'Wrong angle', 'Not sprawling to finish'],
      difficulty: 'advanced', positionContext: 'side_control_top', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'darce', 'choke', 'arm-triangle'], metadata: { positions: ['side_control_top', 'half_guard_top'] }, effectivenessScore: 0.86,
    },
    {
      id: id('ezekiel_choke'), categoryId: 'bjj_cat_sub_chokes', discipline: 'bjj', name: 'Ezekiel Choke',
      japaneseName: 'Sode Guruma Jime', koreanName: null,
      description: 'Choke using the sleeve of your gi. Thread hand inside sleeve, wrap around opponents neck, squeeze.',
      keyPoints: ['Thread hand inside own sleeve', 'Wrap around neck', 'Fist drives into throat', 'Works from mount and guard'],
      commonMistakes: ['Not deep enough', 'Opponent tucks chin', 'Losing position while attacking'],
      difficulty: 'intermediate', positionContext: 'mount_top', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'ezekiel', 'choke', 'gi', 'mount'], metadata: { positions: ['mount_top', 'guard_top'] }, effectivenessScore: 0.79,
    },
    {
      id: id('heel_hook'), categoryId: 'bjj_cat_sub_leglocks', discipline: 'bjj', name: 'Heel Hook',
      japaneseName: null, koreanName: null,
      description: 'Devastating leg lock attacking knee ligaments. Control the leg, cup the heel, rotate.',
      keyPoints: ['Control hip and knee line', 'Cup the heel', 'Rotate toward pinky toe (inside)', 'Ashi garami entry'],
      commonMistakes: ['No hip control', 'Wrong rotation direction', 'Not controlling knee line'],
      difficulty: 'advanced', positionContext: 'leg_entanglement', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'heel-hook', 'leg-lock', 'advanced', 'dangerous'], metadata: { positions: ['leg_entanglement'] }, effectivenessScore: 0.93,
    },
    {
      id: id('knee_bar'), categoryId: 'bjj_cat_sub_leglocks', discipline: 'bjj', name: 'Knee Bar',
      japaneseName: null, koreanName: null,
      description: 'Hyperextend the knee joint. Similar mechanics to armbar but on the leg.',
      keyPoints: ['Control foot/ankle', 'Pinch knees around leg', 'Hips tight against knee', 'Extend hips to finish'],
      commonMistakes: ['Not controlling foot', 'Knees too wide', 'Opponent pulls leg free'],
      difficulty: 'advanced', positionContext: 'leg_entanglement', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'knee-bar', 'leg-lock'], metadata: { positions: ['leg_entanglement'] }, effectivenessScore: 0.85,
    },
    {
      id: id('straight_ankle_lock'), categoryId: 'bjj_cat_sub_leglocks', discipline: 'bjj', name: 'Straight Ankle Lock',
      japaneseName: null, koreanName: null,
      description: 'Basic leg lock. Wrap arm around opponents ankle, blade of wrist on Achilles, arch back.',
      keyPoints: ['Wrist blade on Achilles tendon', 'Pinch knees around their leg', 'Arch back to finish', 'Control their hip with your legs'],
      commonMistakes: ['Wrist not on Achilles', 'Not controlling hip', 'Opponent pulls foot free'],
      difficulty: 'intermediate', positionContext: 'leg_entanglement', videoUrl: null, thumbnailUrl: null,
      tags: ['submission', 'ankle-lock', 'leg-lock', 'fundamental'], metadata: { positions: ['leg_entanglement', 'ashi_garami'] }, effectivenessScore: 0.78,
    },
    // --- Guard Passes ---
    {
      id: id('knee_slice_pass'), categoryId: 'bjj_cat_passes', discipline: 'bjj', name: 'Knee Slice Pass',
      japaneseName: null, koreanName: null,
      description: 'Slide knee across opponents thigh while driving crossface. Fundamental pressure pass.',
      keyPoints: ['Control far hip', 'Slide knee across thigh', 'Crossface pressure', 'Clear legs to side control'],
      commonMistakes: ['Not controlling hip', 'Getting caught in half guard', 'No crossface'],
      difficulty: 'intermediate', positionContext: 'guard_top', videoUrl: null, thumbnailUrl: null,
      tags: ['guard-pass', 'knee-slice', 'pressure', 'fundamental'], metadata: {}, effectivenessScore: 0.88,
    },
    {
      id: id('torreando_pass'), categoryId: 'bjj_cat_passes', discipline: 'bjj', name: 'Torreando (Bullfighter) Pass',
      japaneseName: null, koreanName: null,
      description: 'Grip opponents legs, push to one side, pass around to side control. Fast speed pass.',
      keyPoints: ['Grip both legs', 'Push legs to one side', 'Circle around quickly', 'Establish side control'],
      commonMistakes: ['Not controlling both legs', 'Too slow', 'Not establishing position after'],
      difficulty: 'intermediate', positionContext: 'guard_top', videoUrl: null, thumbnailUrl: null,
      tags: ['guard-pass', 'torreando', 'speed-pass'], metadata: {}, effectivenessScore: 0.85,
    },
    {
      id: id('stack_pass'), categoryId: 'bjj_cat_passes', discipline: 'bjj', name: 'Stack Pass',
      japaneseName: null, koreanName: null,
      description: 'Drive opponents legs over their head, stacking weight on neck. Walk around to side control.',
      keyPoints: ['Drive forward stacking hips', 'Control their legs', 'Walk around while stacked', 'Heavy pressure'],
      commonMistakes: ['Not enough forward pressure', 'Opponent creates angle', 'Getting swept'],
      difficulty: 'intermediate', positionContext: 'guard_top', videoUrl: null, thumbnailUrl: null,
      tags: ['guard-pass', 'stack', 'pressure-pass'], metadata: {}, effectivenessScore: 0.83,
    },
    {
      id: id('leg_drag'), categoryId: 'bjj_cat_passes', discipline: 'bjj', name: 'Leg Drag Pass',
      japaneseName: null, koreanName: null,
      description: 'Drag opponents leg across your body to the opposite side, pin it with your hip, pass to side control.',
      keyPoints: ['Grip their ankle/pants', 'Drag leg across your body', 'Pin with your hip', 'Establish side control or back take'],
      commonMistakes: ['Not pinning the leg', 'Opponent re-guards', 'Not controlling upper body'],
      difficulty: 'intermediate', positionContext: 'guard_top', videoUrl: null, thumbnailUrl: null,
      tags: ['guard-pass', 'leg-drag', 'speed-pass'], metadata: {}, effectivenessScore: 0.86,
    },
    // --- Sweeps ---
    {
      id: id('hip_bump_sweep'), categoryId: 'bjj_cat_sweeps', discipline: 'bjj', name: 'Hip Bump Sweep',
      japaneseName: null, koreanName: null,
      description: 'From closed guard when opponent postures up. Sit up explosively, bump with hip, roll them over.',
      keyPoints: ['Time it when they posture', 'Sit up explosively', 'Post hand behind you', 'Bump hip and roll'],
      commonMistakes: ['Bad timing', 'Not explosive enough', 'Not posting hand'],
      difficulty: 'beginner', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['sweep', 'guard', 'fundamental', 'reversal'], metadata: {}, effectivenessScore: 0.82,
    },
    {
      id: id('scissor_sweep'), categoryId: 'bjj_cat_sweeps', discipline: 'bjj', name: 'Scissor Sweep',
      japaneseName: null, koreanName: null,
      description: 'From guard: shin across stomach, pull forward with collar grip, kick bottom leg and chop top leg.',
      keyPoints: ['Shin across stomach', 'Collar grip pulls forward', 'Bottom leg kicks knee', 'Top leg chops across'],
      commonMistakes: ['Not breaking posture first', 'Legs not scissoring', 'No collar grip'],
      difficulty: 'beginner', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['sweep', 'guard', 'scissor', 'fundamental'], metadata: {}, effectivenessScore: 0.84,
    },
    {
      id: id('butterfly_sweep'), categoryId: 'bjj_cat_sweeps', discipline: 'bjj', name: 'Butterfly Sweep',
      japaneseName: null, koreanName: null,
      description: 'From butterfly guard: get underhook, elevate with hook, fall to side and sweep them over.',
      keyPoints: ['Secure underhook', 'Elevate with hook', 'Fall to the side', 'Come up to top position'],
      commonMistakes: ['No underhook', 'Not elevating enough', 'Falling straight back'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['sweep', 'butterfly', 'guard', 'underhook'], metadata: {}, effectivenessScore: 0.86,
    },
    // --- Escapes ---
    {
      id: id('bridge_and_roll'), categoryId: 'bjj_cat_escapes', discipline: 'bjj', name: 'Bridge and Roll (Upa)',
      japaneseName: null, koreanName: null,
      description: 'Escape from mount. Trap opponents arm and foot on same side, bridge explosively, roll them over.',
      keyPoints: ['Trap arm and foot same side', 'Bridge explosively with hips', 'Turn into them', 'End in their guard'],
      commonMistakes: ['Not trapping arm and foot', 'Weak bridge', 'Bridging straight up not to the side'],
      difficulty: 'beginner', positionContext: 'mount_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['escape', 'mount', 'bridge', 'fundamental'], metadata: {}, effectivenessScore: 0.82,
    },
    {
      id: id('hip_escape'), categoryId: 'bjj_cat_escapes', discipline: 'bjj', name: 'Hip Escape (Shrimp)',
      japaneseName: null, koreanName: null,
      description: 'Fundamental BJJ movement. Push off with feet, slide hips away to create space. Used to escape side control, mount, and re-guard.',
      keyPoints: ['Frame on their hip/shoulder', 'Push off with feet', 'Slide hips away', 'Create space to re-guard'],
      commonMistakes: ['Not framing first', 'Moving upper body not hips', 'Not creating enough space'],
      difficulty: 'beginner', positionContext: 'side_control_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['escape', 'shrimp', 'hip-escape', 'fundamental', 'movement'], metadata: {}, effectivenessScore: 0.85,
    },
    {
      id: id('elbow_knee_escape'), categoryId: 'bjj_cat_escapes', discipline: 'bjj', name: 'Elbow-Knee Escape from Mount',
      japaneseName: null, koreanName: null,
      description: 'From under mount: frame with elbow on their knee, shrimp to create space, insert knee and recover half guard.',
      keyPoints: ['Frame elbow on their knee', 'Shrimp away', 'Insert knee between you', 'Recover to half guard or full guard'],
      commonMistakes: ['Not framing properly', 'Weak shrimp', 'Not inserting knee quickly'],
      difficulty: 'beginner', positionContext: 'mount_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['escape', 'mount', 'elbow-knee', 'fundamental'], metadata: {}, effectivenessScore: 0.84,
    },
    // --- Transitions ---
    {
      id: id('arm_drag'), categoryId: 'bjj_cat_transitions', discipline: 'bjj', name: 'Arm Drag',
      japaneseName: null, koreanName: null,
      description: 'Pull opponents arm across their body to expose their back. Works from guard, standing, or seated.',
      keyPoints: ['Grip their wrist and tricep', 'Pull arm across their body', 'Circle behind them', 'Take the back'],
      commonMistakes: ['Not pulling hard enough', 'Not circling behind', 'Opponent recovers position'],
      difficulty: 'intermediate', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['transition', 'arm-drag', 'back-take', 'setup'], metadata: {}, effectivenessScore: 0.85,
    },
    {
      id: id('berimbolo'), categoryId: 'bjj_cat_transitions', discipline: 'bjj', name: 'Berimbolo',
      japaneseName: null, koreanName: null,
      description: 'Inverted roll to take the back. From de la riva guard, invert under opponent, roll to back control.',
      keyPoints: ['Start from de la riva', 'Invert under them', 'Control their belt/pants', 'Roll to back control'],
      commonMistakes: ['Not inverting deep enough', 'Losing grips', 'Opponent bases out'],
      difficulty: 'advanced', positionContext: 'guard_bottom', videoUrl: null, thumbnailUrl: null,
      tags: ['transition', 'berimbolo', 'back-take', 'advanced', 'inversion'], metadata: {}, effectivenessScore: 0.82,
    },
  ]

  const sequences: SeqSeed[] = [
    {
      id: 'bjj_seq_armbar_triangle', discipline: 'bjj', name: 'Armbar-Triangle-Omoplata Chain', description: 'Classic guard submission chain. If one fails, transition to the next.',
      steps: [
        { techniqueId: id('armbar'), notes: 'Attack armbar from guard', transitionCue: 'If they stack, switch to triangle' },
        { techniqueId: id('triangle_choke'), notes: 'Lock triangle as they defend armbar', transitionCue: 'If they posture, switch to omoplata' },
        { techniqueId: id('omoplata'), notes: 'Omoplata as they pull arm out', transitionCue: 'Finish or sweep' },
      ],
      difficulty: 'intermediate', tags: ['chain', 'guard', 'submissions'],
    },
    {
      id: 'bjj_seq_pass_mount_sub', discipline: 'bjj', name: 'Pass-Mount-Submit', description: 'Complete top game sequence.',
      steps: [
        { techniqueId: id('knee_slice_pass'), notes: 'Pass guard with knee slice', transitionCue: 'Establish side control' },
        { techniqueId: id('side_control'), notes: 'Consolidate side control', transitionCue: 'Transition to mount' },
        { techniqueId: id('mount'), notes: 'Secure mount', transitionCue: 'Attack submission' },
        { techniqueId: id('armbar'), notes: 'Armbar from mount', transitionCue: 'Finish' },
      ],
      difficulty: 'intermediate', tags: ['chain', 'top-game', 'complete'],
    },
    {
      id: 'bjj_seq_sweep_pass', discipline: 'bjj', name: 'Sweep to Pass to Back Take', description: 'Bottom to dominant position.',
      steps: [
        { techniqueId: id('butterfly_sweep'), notes: 'Butterfly sweep to top', transitionCue: 'Opponent turtles' },
        { techniqueId: id('arm_drag'), notes: 'Arm drag as they turtle', transitionCue: 'Expose the back' },
        { techniqueId: id('back_control'), notes: 'Secure back control', transitionCue: 'Attack RNC' },
        { techniqueId: id('rear_naked_choke'), notes: 'Finish with RNC', transitionCue: 'Submit' },
      ],
      difficulty: 'advanced', tags: ['chain', 'complete-game', 'back-take'],
    },
    {
      id: 'bjj_seq_guard_retention', discipline: 'bjj', name: 'Guard Retention Flow', description: 'Cycling through guards to prevent pass.',
      steps: [
        { techniqueId: id('closed_guard'), notes: 'Start in closed guard', transitionCue: 'If they stand, open to DLR' },
        { techniqueId: id('de_la_riva'), notes: 'De La Riva to control standing opponent', transitionCue: 'If they kill hook, go to spider' },
        { techniqueId: id('spider_guard'), notes: 'Spider guard for distance', transitionCue: 'If they pass, recover half guard' },
        { techniqueId: id('half_guard'), notes: 'Half guard as last line', transitionCue: 'Underhook and re-guard or sweep' },
      ],
      difficulty: 'intermediate', tags: ['guard-retention', 'flow', 'defense'],
    },
  ]

  const counters: CounterSeed[] = [
    { id: 'bjj_ctr_1', techniqueId: id('armbar'), counterTechniqueId: id('stack_pass'), effectiveness: 'high', notes: 'Stack and pull arm free' },
    { id: 'bjj_ctr_2', techniqueId: id('triangle_choke'), counterTechniqueId: id('stack_pass'), effectiveness: 'high', notes: 'Posture up and stack to relieve pressure' },
    { id: 'bjj_ctr_3', techniqueId: id('guillotine'), counterTechniqueId: id('knee_slice_pass'), effectiveness: 'high', notes: 'Pass to side control to relieve choke' },
    { id: 'bjj_ctr_4', techniqueId: id('kimura'), counterTechniqueId: id('armbar'), effectiveness: 'medium', notes: 'Straighten arm to escape kimura into armbar threat' },
    { id: 'bjj_ctr_5', techniqueId: id('closed_guard'), counterTechniqueId: id('knee_slice_pass'), effectiveness: 'high', notes: 'Open guard and pass' },
    { id: 'bjj_ctr_6', techniqueId: id('mount'), counterTechniqueId: id('bridge_and_roll'), effectiveness: 'high', notes: 'Trap arm and foot, bridge and roll' },
    { id: 'bjj_ctr_7', techniqueId: id('mount'), counterTechniqueId: id('elbow_knee_escape'), effectiveness: 'high', notes: 'Frame and shrimp to half guard' },
    { id: 'bjj_ctr_8', techniqueId: id('side_control'), counterTechniqueId: id('hip_escape'), effectiveness: 'high', notes: 'Frame and shrimp to re-guard' },
    { id: 'bjj_ctr_9', techniqueId: id('back_control'), counterTechniqueId: id('bridge_and_roll'), effectiveness: 'medium', notes: 'Turn into them and escape to guard' },
    { id: 'bjj_ctr_10', techniqueId: id('knee_slice_pass'), counterTechniqueId: id('half_guard'), effectiveness: 'medium', notes: 'Catch half guard and underhook' },
    { id: 'bjj_ctr_11', techniqueId: id('heel_hook'), counterTechniqueId: id('straight_ankle_lock'), effectiveness: 'medium', notes: 'Counter-attack their leg while defending' },
  ]

  return { categories, entries, sequences, counters }
}
