// Generated by Wrangler (`pnpm cf-typegen`) — hand-maintained bindings below.
// Re-run cf-typegen after changing wrangler.toml.

interface CloudflareEnv {
  DB: D1Database
  ASSETS: Fetcher
  VECTORIZE: VectorizeIndex
  AI: Ai
  WORKER_SELF_REFERENCE: Fetcher
}
