import Link from 'next/link'
import { ArrowLeft, ScrollText } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

function Section({ title, children }: Readonly<{ title: string; children: React.ReactNode }>) {
  return (
    <section className="space-y-2">
      <h2 className="text-base font-semibold tracking-tight text-foreground">{title}</h2>
      <div className="space-y-2 text-sm leading-relaxed text-muted-foreground">{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-background text-foreground">
      <div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-primary/10 via-transparent to-primary/5" />
      <div className="pointer-events-none absolute inset-0 bg-[url('/grid.svg')] opacity-[0.05]" />

      <div className="container relative mx-auto max-w-2xl px-4 py-12 lg:py-16">
        <Card className="border-border/60 bg-card/80 shadow-xl backdrop-blur-sm">
          <CardHeader className="space-y-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-primary/15 text-primary ring-1 ring-primary/20">
              <ScrollText className="h-6 w-6" aria-hidden="true" />
            </div>
            <CardTitle className="text-2xl tracking-tight">Terms of Service</CardTitle>
            <CardDescription>Last updated: June 2026</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <Section title="1. Acceptance of Terms">
              <p>
                By creating an account or using Musashi (the &ldquo;Service&rdquo;), you agree to be
                bound by these Terms of Service. If you do not agree to these terms, do not use the
                Service. We may update these terms from time to time; continued use of the Service
                after changes take effect constitutes acceptance of the revised terms.
              </p>
            </Section>

            <Section title="2. Description of the Service">
              <p>
                Musashi is an AI-powered fight-analysis and training platform. The Service lets you
                upload training and sparring footage, receive automated pose and technique analysis,
                track progress, and connect with coaches and other fighters. Features may change,
                be added, or be removed at any time.
              </p>
            </Section>

            <Section title="3. Your Account">
              <p>
                You are responsible for maintaining the confidentiality of your account credentials
                and for all activity that occurs under your account. You must provide accurate
                information and be at least the age of majority in your jurisdiction (or have
                consent from a parent or guardian) to use the Service.
              </p>
            </Section>

            <Section title="4. User Content and Video Uploads">
              <p>
                You retain ownership of the videos, images, and other content you upload. By
                uploading content, you grant Musashi a limited license to store, process, and
                analyze it solely for the purpose of providing the Service to you. You are
                responsible for ensuring you have the right to upload any footage, including
                consent from other people who appear in it. You must not upload content that is
                unlawful, infringing, or abusive.
              </p>
            </Section>

            <Section title="5. AI-Generated Content Disclaimer">
              <p>
                Coaching insights, technique analysis, scores, and recommendations produced by the
                Service are generated by automated systems and are provided for informational
                purposes only. They do not constitute medical, health, safety, or professional
                coaching advice. Combat sports carry inherent risk of injury; always train under
                qualified supervision and consult a physician before beginning or modifying any
                training program. Musashi is not responsible for decisions you make based on
                AI-generated output.
              </p>
            </Section>

            <Section title="6. Payments and Subscriptions">
              <p>
                Some features require a paid subscription. Prices are shown at checkout and billed
                through our payment processor. Subscriptions renew automatically until cancelled.
                You may cancel at any time; access continues until the end of the current billing
                period. Except where required by law, payments are non-refundable.
              </p>
            </Section>

            <Section title="7. Acceptable Use">
              <p>
                You agree not to misuse the Service, including by attempting to access other users&rsquo;
                data, reverse-engineering the platform, scraping content, or using the Service to
                harass others or violate any applicable law.
              </p>
            </Section>

            <Section title="8. Limitation of Liability">
              <p>
                To the maximum extent permitted by law, Musashi and its affiliates are not liable
                for any indirect, incidental, special, consequential, or punitive damages, or for
                any loss of data, profits, or goodwill, arising from your use of the Service. The
                Service is provided &ldquo;as is&rdquo; without warranties of any kind. Our total
                liability for any claim related to the Service is limited to the amount you paid us
                in the twelve months preceding the claim.
              </p>
            </Section>

            <Section title="9. Termination">
              <p>
                We may suspend or terminate your account if you violate these terms. You may delete
                your account at any time, after which your content will be removed in accordance
                with our Privacy Policy.
              </p>
            </Section>

            <Section title="10. Contact">
              <p>
                Questions about these terms can be sent to support via the contact options in the
                app or to the Musashi support email listed on our website.
              </p>
            </Section>

            <p className="text-xs italic leading-relaxed text-muted-foreground/70">
              This is a general template provided for review; consult a lawyer before public
              launch.
            </p>

            <div className="flex flex-wrap gap-2 pt-2">
              <Button variant="outline" className="h-10" asChild>
                <Link href="/signup">
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  Back to signup
                </Link>
              </Button>
              <Button variant="ghost" className="h-10 text-muted-foreground hover:text-foreground" asChild>
                <Link href="/privacy">Privacy Policy</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
